name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          key: ${{ runner.os }}-rate-limit-${{ hashFiles('**/deps.edn') }}
          restore-keys: ${{ runner.os }}-rate-limit
          path: |
            ~/.gitlibs
            ~/.m2
            deps

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: DeLaGuardo/setup-clojure@3.1
        with:
          cli: '1.10.2.796'

      - run: clojure -M:test -e :redis
